config/routes.rb
Rails.application.routes.draw do
  resources :movies do
    resources :reviews
  end 
  
  resources :reviews

  resources :users do 
    resources :reviews
    resources :movies
  end 

  

  # http request     controller       path
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  match '/auth/github/', to: 'sessions#create', via: [:get, :post]
  post "sessions", to: "sessions#create", as: "sessions"

  get 'auth/github/callback', to: "sessions#create"
  
  
  
  patch 'reviews/:id', to: 'reviews#update'

  get "homepage", to: "home#index", as: "homepage"
  
  
  delete "sessions", to: "sessions#destroy", as: "logout"

  root 'home#index'

end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews

    validates :title, presence: true
    validates :title, uniqueness: true
    
    scope :most_reviews, -> {order(reviews_count: :desc)}
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :movie, counter_cache: true

    validates :content, presence: true
    validates :rating, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :reviews
    has_many :movies, through: :reviews
    
    validates :username, uniqueness: true
    validates :username, :password, presence: true

    scope :most_reviews, -> { joins(:reviews).group(:count).first }
    # joins the users(self) and reviews db, maps through them, and selects the user with the most reviews associated with it
                # auth is a hash coming from github
    def self.find_or_create_by_omniauth(auth)
        user = User.find_by(uid: auth['uid'])

        if user.nil?
            user = User.create(email: auth['info']['email'], username: auth['info']['nickname'], password: SecureRandom.hex, uid: auth['uid'])
        elsif user.uid.nil?
            user.update(uid: auth['uid'])
        end 
        user 
    end 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    helper_method :logged_in?

    def current_user 
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
        end 
    end 

    def logged_in?
        !!current_user
    end 

    


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end 
    
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    def index
        if params[:user_id]
            @user = User.find(params[:user_id])
            @movies = @user.movies 
        else
            @movies = Movie.all 
        end 
            
        if params[:sort_order] == "most_reviewed"

    
            @movies = @movies.most_reviews
            
        end
        
    end 

    def new
        @movie = Movie.new
    end 

    def create 
        @movie = Movie.new(movie_params)
        if @movie.save 
            @user = current_user 
            
            
             redirect_to @user
            
        else 
            render :new 
        end 
    end 

    def show 
        @movie = Movie.find(params[:id]) 
    end 

    private

    def movie_params
        params.require(:movie).permit(:title)
    end 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    

    def index
        if params[:user_id]
            @user = User.find(params[:user_id])
            @reviews = @user.reviews 
        else
            @reviews = Review.all 
        end 
    end 

    def new
        @review = Review.new
        @movie = Movie.find_by id: params[:movie_id]
    end 

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save 
            redirect_to '/reviews'
            else 
            render 'new'
             end 
        end 
        


    def edit 
        @review = Review.find(params[:id])
        
    end 

    def update
        @review = Review.find(params[:id])

        if @review.update(review_params)
            redirect_to '/reviews'
        else 
            render 'edit'
        end 
        
    end 

    def show
        @review = current_user.reviews
    end 

    def destroy
        @review = Review.find(params[:id]) 
        @review.destroy
        redirect_to '/reviews'
    end 

    private

    def review_params
        params.require(:review).permit(:rating, :content, :movie_id, :user_id)
    end 

    


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
    end 

    def create
        # finds the user then authenticates the user by comparing the password in the db vs the password the user entered
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            redirect_to @user 
        else 
            render login_path
        end 
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end 

    def create

        if request.env['omniauth.auth']	
            @user = User.find_or_create_by_omniauth(auth)
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
        # finds the user then authenticates the user by comparing the password in the db vs the password the user entered
        @user = User.find_by(username: params[:username])
            if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to @user 
            else 
             redirect_to login_path 
            end
        end 
    end 

    def destroy
        session.delete(:user_id)

        redirect_to homepage_path 
    end 

    private
    def auth
        request.env['omniauth.auth']
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    helper_method :set_user
    

    def index
        @users = User.all
    end 

    def show
        set_user
    end 

    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id 
            redirect_to @user 
        else 
            render :new 
        end 
    end 

    def edit 
        if current_user != set_user
            redirect_to current_user
        end 
    end 

    def update
        set_user
        if @user.update_attributes(user_params)
            redirect_to @user 
        else 
            render 'edit'
        end 
    end 

    private

    def set_user
       @user = User.find(params[:id])
    end 

    def user_params
        params.require(:user).permit(:name, :username, :password, :uid, :provider)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
WELCOME TO MOVIE VOID!

WHERE YOU CAN SCREAM ABOUT YOUR FAVORITE (OR LEAST FAVORITE) MOVIE TO YOUR HEARTS CONTENT!!!!

<br>
<% if current_user %>
<%= link_to "My Page", user_path(current_user)%>
<%end %>
 <br>
 <br>

<%= link_to "Login", login_path %> | 
 |
<%= link_to "Sign Up", signup_path %>
<br>
<br>
Take a look at all the Movies our users have reviewed!
 <br>
<%= link_to "Movies", movies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieVoid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<strong>Movies</strong>
<br>

<%= form_tag({}, {:method => :get}) do %>
    <select name = "sort_order">
    <option>"Enter"</option>
    <option value = "most_reviewed"> Most Reviews</option>
     </select>
     <%= submit_tag %>
<% end %>

<% @movies.each do |m| %>

<li><%= m.title %> | <%= link_to "More Details", movie_path(m.id) %></li>


<% end %>

<%= link_to "homepage", homepage_path %>

<% if current_user %>
    <%= link_to "My Page", user_path(current_user)%>
<% end %>

app/views/movies/new.html.erb
<%= form_for @movie do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.submit %>
<% end %>

<%= link_to "Return To My Page", user_path(current_user)%>

app/views/movies/show.html.erb
<strong><%= @movie.title %></strong>
<br>
Number of Reviewers: <strong><%= @movie.users.count %> </strong>
<br>
Number of Reviews: <strong><%= @movie.reviews.count %> </strong>
<br>
<br>
What Users Are Saying! <% @movie.reviews.map do |r| %>
<li> <%= r.content %> - <%= r.user.username %>
    
<% end %>
<br>
<br>
 

<br>




<%= link_to "Add A Review", new_movie_review_path(@movie) %>
<br>
<br>
<%= link_to "Movies", movies_path %>
<br>
<%= link_to "My Page", user_path(current_user)%>
<br>
<%= link_to "Home", homepage_path %>

app/views/reviews/_form.html.erb
<%= form_for @review do |f| %>
    <%= f.label :movie %>
    <%= f.collection_select :movie_id, Movie.all, :id, :title %>
    <%= f.label :rating %>
    <%= f.number_field :rating, required: true %>
    <%= f.label :content %>
    <%= f.text_area :content, required: true %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
EDIT A REVIEW
<%= form_for @review do |f| %>
    <%= f.label :movie %>
    <%= f.collection_select :movie_id, Movie.all, :id, :title %>
    <%= f.label :rating %>
    <%= f.number_field :rating %>
    <%= f.label :content %>
    <%= f.text_area :content %>
    <%= f.hidden_field :user_id %>
    <%= f.submit %>
<% end %>
<%= link_to "My Page", user_path(current_user)%>

app/views/reviews/index.html.erb
<ul>
<% @reviews.each do |r| %>

<br>
<br>
<li> <strong>Movie:</strong> <%= r.movie.title %> 
    <br>
 <li><strong>Rating:</strong> <%= r.rating %>
    <br>
<li> <strong>Review:</strong> <%= r.content %>
    <br>
<li> <strong>Reviewer:</strong> <%= r.user.username %>
    <br>
    <% if current_user.id == r.user_id %>
    <%= link_to "Edit", edit_review_path(r.id) %> |
    <%= link_to "Delete", user_reviews_path(current_user, r.id) , method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>


<% end %>
<br>
<br>
<%= link_to "My Page", user_path(current_user)%>
</ul>

app/views/reviews/new.html.erb
Select The Movie You'd Like To Review!
<br>

<%= form_for @review do |f| %>

    
    <%= f.label :movie %>
 <% if @movie %>
     <%= @movie.title %>
     <%= f.hidden_field(:movie_id, :value => params[:movie_id]) %>
    <% else %> 
    <%= f.collection_select :movie_id, Movie.all, :id, :title %>
   <% end %>

    <%= f.label :rating %>
    <%= f.number_field :rating, min: 1, max: 10 %>
    <%= f.label :content %>
    <%= f.text_area :content %>
    <%= f.hidden_field :user_id %>
    <%= f.submit %>

<% end %>

<%= link_to "Return To My Page", user_path(current_user)%>

<%# the hidden_field sends us back the user_id %>

app/views/reviews/show.html.erb
MY REVIEWS
<br>
<% @user.reviews.each do |r| %>
<li><%= r.movie.title%> 
<% end %>


<br>
<br>
<%= link_to "My Page", user_path(@user) %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited you from saving:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
<div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%=f.label :password %>
    <%= f.password_field :password %>
    <%=f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit %>
</div>
<% end %>

app/views/users/edit.html.erb
 Edit your account information here
 <br>
<br>
<%= render "form" %>

<br>
<br>
<%= link_to "Return To My Page", user_path(current_user)%>

app/views/users/index.html.erb
Meet our reviewers!
<br>
<br>
    <% @users.each do |u| %>
    <li><%= u.username %></li>
    
    <% end %>

    <br>
    <br>
    Come add your name to our reviewer list!

    <%= link_to "Home", homepage_path %>

app/views/users/new.html.erb
<%= render "form" %>
<%= link_to "Login", login_path %>

app/views/users/show.html.erb
<% if current_user != set_user %>
<strong>We Miss You! <%= @user.username %> </strong>
<% else %>
<strong>Welcome Back, <%=@user.username %>!</strong>
<% end %>




<br>
<% if current_user != set_user %>
<%= link_to "login", login_path %>
<br>
<%= link_to "Home", homepage_path %>
   <% else %>
   
    <br>
    <%= link_to "My Reviews", user_reviews_path(current_user) %>
    <br> 
    <%= link_to "All Reviews", reviews_path %>
    <br>
    <%= link_to "Leave A Review", new_review_path %>
    <br>
    <%= link_to "Add A Movie", new_movie_path(current_user) %>
    <br>
    <%= link_to "Movies", movies_path  %>
    <br>
    <%= link_to "Edit My Account", edit_user_path(current_user)%>
    <br>
     <%= link_to "Logout", sessions_path(current_user), :method => :delete, :class=>:destroy %>
<% end %>